Landing Page
aarontorres0/HomieHub pull request #2
Opened 2023-10-18 07:03 UTC by isaac342368

2023-10-19 16:52 UTC, jlipscomb071 reviewed
Left some comments. We should meet to talk a bit more about the design of the landing page.

2023-10-19 16:52 UTC, jlipscomb071 commented on Components/LandingPage.jsx
> +      colors={['#6a11cb', '#2575fc']}
I think the landing page is pretty blue. I'd suggest a predominantly white landing page with blue accents. The blue makes certain text harder to read.

2023-10-19 16:52 UTC, jlipscomb071 commented on Components/LandingPage.jsx
> +      <Text style={styles.welcomeText}>Welcome to HomieHub</Text>
The font of the Welcome text could be a bit more unique. I know we didn't agree on a font, so maybe we can agree on one moving forward.

2023-10-19 16:52 UTC, jlipscomb071 commented on Components/LandingPage.jsx
> +        <Text style={styles.buttonText}>Log In</Text>
I think rounded buttons would make the page more modern.

2023-10-19 16:52 UTC, jlipscomb071 commented on Components/LandingPage.jsx
> +const styles = StyleSheet.create({
Maybe we should store this css in a separate file? I'd assume we'll end up recycling some of it for other pages.

2023-10-19 17:01 UTC, aarontorres0 requested changes

2023-10-19 17:01 UTC, aarontorres0 commented on Components/LandingPage.jsx
> +    width: '100%', // Full width
nit: comment not necessary

2023-10-19 17:01 UTC, aarontorres0 commented on Components/LandingPage.jsx
> +      </TouchableOpacity>
I've noticed most apps have the register button and then the login button. We could switch the order of these buttons here

2023-10-19 17:01 UTC, aarontorres0 commented on Components/LandingPage.jsx
> +      colors={['#6a11cb', '#2575fc']}
These colors are pretty dark and similar. Having the background be white would provide a better contrast

2023-10-19 17:01 UTC, aarontorres0 commented on Components/LandingPage.jsx
> +    height: '60%', // Made video larger by occupying 50% of screen height
nit: unnecessary comment

2023-10-30 22:38 UTC, jlipscomb071 commented
We're gonna merge the other PR instead.

2023-10-30 22:38 UTC, closed without merging